# INSTALL PLUGIN RELLOAD
unless Vagrant.has_plugin?("vagrant-reload")
  puts 'Installing vagrant-reload Plugin...'
  system('vagrant plugin install vagrant-reload')
end

Vagrant.configure("2") do |config|

  #FIX VGUEST WARNN
  if Vagrant.has_plugin? "vagrant-vbguest"
    config.vbguest.no_install  = true
    config.vbguest.no_remote   = true
    config.vbguest.auto_update = false
  end

  # Set Box
  config.vm.box = "debian/bullseye64"
  #config.vm.box = "boxomatic/debian-12"
  config.vm.box_download_insecure=true

  # VM Debian Server
  config.vm.define "debian_skynet"  do |debian_skynet|

    # VARIABLE HOSTNAME
    APP_NAME= "debian-skynet"

    # HOSTNAME
    debian_skynet.vm.hostname = APP_NAME

    # NETWORK
    debian_skynet.vm.network "public_network",ip: "192.168.0.140",mode: "bridge",bridge: "Intel(R) I211 Gigabit Network Connection"
    debian_skynet.vm.network "private_network",ip: "172.36.12.230"

    # MOUNTS
    debian_skynet.vm.synced_folder ".", "/vagrant", disabled: true
    debian_skynet.vm.synced_folder "./security", "/home/vagrant/security"
    debian_skynet.vm.synced_folder "./configs", "/home/vagrant/configs"
    debian_skynet.vm.synced_folder "../ansible/", "/home/vagrant/ansible"
    debian_skynet.vm.synced_folder "../packer/", "/home/vagrant/packer"
    debian_skynet.vm.synced_folder "../terraform", "/home/vagrant/terraform"

    # PROVIDER CUSTOMIZATIONS
    debian_skynet.vm.provider "virtualbox" do |vb|
      vb.linked_clone = true
      vb.name = APP_NAME
      vb.memory = 4096
      vb.cpus = 3
    end

    # PROVISION
    debian_skynet.vm.provision "shell", path: "scripts/install.sh"

  end
end